/run/initialize
/vis/open OGL 
/vis/viewer/set/autoRefresh false
/vis/verbose errors

/vis/drawVolume

/vis/viewer/set/viewpointThetaPhi 120 150 deg
/vis/viewer/zoom 1

/vis/viewer/set/style surface
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100

/vis/scene/add/axes 0 0 0 10 cm
/vis/scene/add/scale 10 cm z 1 0 0 manual 10 0 0 cm # Barra de escala

/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/scene/endOfEventAction accumulate

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow
/vis/modeling/trajectories/drawByParticleID-0/set alpha cyan

/vis/viewer/set/autoRefresh true
/vis/verbose warnings